# Generated by Django 3.2.8 on 2021-11-29 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('User_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('User_email', models.EmailField(max_length=200)),
                ('User_Phone', models.CharField(max_length=10)),
                ('Subscription_type', models.CharField(max_length=200)),
                ('Creation_date', models.DateField()),
                ('Name', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('User_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='view_table',
            fields=[
                ('view_id', models.IntegerField(primary_key=True, serialize=False)),
                ('view_contact', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Score_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Method', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=1)),
                ('Score_id', models.CharField(max_length=200)),
                ('Creation_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_date_of_record', to='contacts_app.user_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Save_search',
            fields=[
                ('search_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Search_Criteria', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Method_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fields', models.CharField(max_length=200)),
                ('Weightage', models.IntegerField()),
                ('Score_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_id_for_matrix', to='contacts_app.score_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='Limit_table',
            fields=[
                ('limit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Total_limit', models.IntegerField()),
                ('validation_date', models.DateField()),
                ('balance', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_app.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_table',
            fields=[
                ('Contact_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Contact_type', models.CharField(max_length=200)),
                ('Full_name', models.CharField(max_length=200)),
                ('First_name', models.CharField(max_length=200)),
                ('Middle_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Emailid', models.EmailField(max_length=200)),
                ('Aadhar', models.CharField(max_length=12)),
                ('Pan_card', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=10)),
                ('Title', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('University', models.CharField(max_length=200)),
                ('Degree', models.CharField(max_length=200)),
                ('Passing_year', models.IntegerField()),
                ('College', models.CharField(max_length=200)),
                ('LinkedIN', models.URLField()),
                ('Facebook', models.URLField()),
                ('Instagram', models.URLField()),
                ('Industry', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Zip', models.IntegerField()),
                ('Key_Skills', models.CharField(max_length=200)),
                ('Total_Experience', models.CharField(max_length=200)),
                ('Years_in_Business', models.CharField(max_length=200)),
                ('CIN_No', models.CharField(max_length=200)),
                ('Turnover', models.CharField(max_length=200)),
                ('Date_of_Incorporation', models.DateField()),
                ('Employees', models.CharField(max_length=200)),
                ('CTC', models.CharField(max_length=200)),
                ('Notes', models.CharField(max_length=200)),
                ('Remarks', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_app.user_table')),
            ],
        ),
    ]
