# Generated by Django 3.2.8 on 2021-12-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='subscription_type',
            field=models.CharField(max_length=200),
        ),
    ]
