# Generated by Django 3.2.8 on 2021-12-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0002_alter_userdata_subscription_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='score',
            new_name='method',
        ),
    ]
