# Generated by Django 3.2.8 on 2021-12-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0003_rename_score_method_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='total_limits',
            field=models.IntegerField(null=True),
        ),
    ]
