# Generated by Django 3.2.8 on 2021-12-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0004_auto_20211206_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='method',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='method',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='method',
            name='weightage',
        ),
        migrations.AddField(
            model_name='method',
            name='type',
            field=models.CharField(default='predefined', max_length=10),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weightage', models.IntegerField(default=0)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_app.method')),
            ],
        ),
    ]
