# Generated by Django 3.2.8 on 2021-12-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0005_auto_20211207_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
