# Generated by Django 3.2.8 on 2021-12-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0010_usercontactscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='balance',
            new_name='viewed',
        ),
    ]
