# Generated by Django 3.2.8 on 2021-12-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0011_rename_balance_userdata_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
