# Generated by Django 3.2.8 on 2021-12-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0014_auto_20211210_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='score',
            name='method',
        ),
        migrations.RemoveField(
            model_name='score',
            name='status',
        ),
        migrations.AddField(
            model_name='score',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contacts_app.contact'),
        ),
        migrations.AddField(
            model_name='score',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
