# Generated by Django 3.2.8 on 2021-12-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0015_auto_20211210_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='current_method',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='contacts_app.method'),
        ),
    ]
