# Generated by Django 3.2.8 on 2021-12-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0016_userdata_current_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='current_method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contacts_app.method'),
        ),
    ]
