# Generated by Django 3.2.8 on 2021-12-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0018_delete_usercontactscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='subscription_type',
        ),
    ]
