from django.db import models

class Contact_table(models.Model):
	Contact_type=models.CharField()
	Full_name=models.CharField()
	First_name=models.CharField()
	Middle_name=models.CharField()
	Last_name=models.CharField()
	Company=models.CharField()
	Designation=models.CharField()
	Emailid=models.EmailField()
	Aadhar=models.CharField(max_length=12)
	Pan_card=models.CharField(max_length=10)
	Phone=models.CharField(max_length=10)
	Location=models.CharField()
	Gender=models.CharField(max_length=1)
	Title=models.CharField()
	Department=models.CharField()
	University=models.CharField()
	Degree=models.CharField()
	Passing_year=models.IntegerField()
	College=models.CharField()
	LinkedIN=models.URLField()
	Facebook=models.URLField()
	Instagram=models.URLField()
	Industry=models.CharField()
	Country=models.CharField()
	State=models.CharField()
	Zip=models.IntegerField()
	Key_Skills=models.CharField()
	Total_Experience=models.CharField()
	Years_in_Business=models.CharField()
	CIN_No=models.CharField()
	Turnover=models.CharField()
	Date_of_Incorporation=models.DateField()
	Employees=models.CharField()
	CTC=models.CharField()
	Notes=models.CharField()
	Remarks=models.CharField()
	User_ID=models.CharField(primary_key=True)

class User_table(models.Model):
	Username=models.CharField()
	Password=models.CharField()
	User_email=models.EmailField()
	User_Phone=models.CharField(max_length=10)
	Subscription_type=models.CharField()
	Creation_date=models.DateField()
	Name=models.CharField()
	Status=models.CharField()
	User_type=models.CharField()
